<?php

function dna_menu() {
  $items['dna'] = array(
    'title'           => 'DNA Completer',
    'page callback'   => 'drupal_get_form',
    'page arguments'  => array('dna_form'),
    'access callback' => TRUE,
    'type'            => MENU_NORMAL_ITEM,
  );

  $items['dna_success_page'] = array(
    'title'           => 'Success!',
    'page callback'   => 'dna_success',
    'access callback' => TRUE,
    'type'            => MENU_CALLBACK,
  );
  return $items;
}

function dna_form() {
  $form['sequence'] = array(
    '#title'        => 'DNA Sequence',
    '#type'         => 'textfield',
    '#description'  => t("Provide a DNA sequence in a format similar to this: 'ATTACG.'"),
    '#element_validate' => array('element_validate_nucleotides'),
  );

  $form['submit'] = array(
    '#type'   => 'submit',
    '#value'  => 'Complete Sequence',
  );
  return $form;
}

//Validation. Ensure users enter only A,T,C,G.
function element_validate_nucleotides($element, $form_state) {
  $input = $form_state['values']['sequence'];
  $input_array = str_split(strtoupper($input));
  if (!in_array('A',$input_array) &&
      !in_array('T',$input_array) &&
      !in_array('C',$input_array) &&
      !in_array('G',$input_array)) {

        form_error($element, t("You may only enter the letters 'A, T, C, G' as nucleotides."));
  }
}

function complete_dna($sequence) {
  //Make sure sequence is upper cased.
  $uppercase_sequence = strtoupper($sequence);
  //Explode into array.
  $letters = str_split($uppercase_sequence);

  //Setup array for other half of sequence.
  $opposites = array();
  //Iterate through $sequence.
  foreach ($letters as $letter) {
    if ($letter == 'A') {
      array_push($opposites, 'T');
    } elseif ($letter == 'T') {
      array_push($opposites, 'A');
    } elseif ($letter == 'G') {
      array_push($opposites, 'C');
    } elseif ($letter == 'C') {
      array_push($opposites, 'G');
    }
  }
  //Implode and return results.
  $results = implode($opposites);
  return $results;
}

function dna_form_submit($form, &$form_state) {
  $sequence = $form_state['values']['sequence'];

  $_SESSION['dna_output'] = complete_dna($sequence);

  $form_state['redirect'] = 'dna_success_page';
}

function dna_success() {
  $result = $_SESSION['dna_output'];
  return $result;
}
